export const ActionTypes = {
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    SET_FILTERED_POSTS: "SET_FILTERED_POSTS",
    SET_SELECTED_USER: "SET_SELECTED_USER",
    ERROR_OCCURRED: "ERROR_OCCURRED",
  };
  